BlogApp.WebUI/Controllers/BlogController.cs
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository _blogRepository;
        private ICategoryRepository _categoryRepository;

        public BlogController(IBlogRepository blogRepo, ICategoryRepository categoryRepo)
        {
            _blogRepository = blogRepo;
            _categoryRepository = categoryRepo;
        }

        //Index
        public IActionResult Index(int? id, string q)
        {
            var query = _blogRepository.GetAll().Where(x => x.IsApproved);
            if (id != null)
            {
                query = query.Where(x => x.CategoryId == id);
            }
            if (!string.IsNullOrEmpty(q))
            {
                //query = query.Where(x => x.Title.Contains(q) || x.Description.Contains(q) || x.Body.Contains(q));
                query = query.Where(x => EF.Functions.Like(x.Title, "%" + q + "%") || EF.Functions.Like(x.Description, "%" + q + "%") || EF.Functions.Like(x.Title, "%" + q + "%"));
            }
            return View(query.OrderByDescending(x => x.Date));
        }

        //Details
        public IActionResult Details(int id)
        {
            return View(_blogRepository.GetById(id));
        }
        //List
        public IActionResult List()
        {
            return View(_blogRepository.GetAll());
        }

        //Create
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(new Blog());
        }
        [HttpPost]
        public async Task<IActionResult> Create(Blog entity, IFormFile file)
        {
            entity.Date = DateTime.Now;
            if (ModelState.IsValid)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                entity.Image = file.FileName;
                _blogRepository.AddBlog(entity);
                TempData["Message"] = $"{entity.Title} Kayıt Edildi.";
                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(entity);
        }

        //Edit
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(_blogRepository.GetById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Blog entity, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    entity.Image = file.FileName;
                }
                _blogRepository.UpdateBlog(entity);
                TempData["Message"] = $"{entity.Title} Güncellendi.";
                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(entity);
        }

        //Delete
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_blogRepository.GetById(id));
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int blogId)
        {
            _blogRepository.DeleteBlog(blogId);
            TempData["Message"] = $"{blogId} numaralı ID'ye Sahip Kayıt Silindi.";
            return RedirectToAction("List");
        }


        #region Create (Çeşitli Denemelerden Dolayı Fazla Fazla Fonksiyon Var)
        ////Create
        //[HttpGet]
        //public IActionResult Create()
        //{
        //    ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
        //    return View(new Blog());

        //}

        //[HttpPost]
        //public IActionResult Create(Blog entity)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _blogRepository.AddOrUpdate(entity);
        //        TempData["Message"] = $"{entity.Title} Kayıt Edildi.";
        //        return RedirectToAction("List");
        //    }
        //    ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
        //    return View(entity);
        //}

        ////Edit
        //[HttpGet]
        //public IActionResult Edit(int id)
        //{
        //    ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");

        //    return View(_blogRepository.GetById(id));
        //}

        //[HttpPost]
        //public async Task<IActionResult> Edit(Blog entity, IFormFile file)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        if (file != null)
        //        {
        //            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);
        //            using (var stream = new FileStream(path, FileMode.Create))
        //            {
        //                await file.CopyToAsync(stream);
        //            }

        //            entity.Image = file.FileName;
        //        }

        //        _blogRepository.AddOrUpdate(entity);
        //        TempData["Message"] = $"{entity.Title} Kayıt Edildi.";
        //        return RedirectToAction("List");
        //    }
        //    ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
        //    return View(entity);
        //}


        #endregion

        #region Add or Update (Tek sayfa üzerinden yapmak için kullanılan method)

        ////Add or Update
        //[HttpGet]
        //public IActionResult AddOrUpdate(int? id)
        //{
        //    ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
        //    if (id == null)
        //    {
        //        //yeni kayıt
        //        return View(new Blog());
        //    }
        //    else
        //    {
        //        //güncelleme
        //        return View(_blogRepository.GetById((int)id));
        //    }
        //}

        //[HttpPost]
        //public IActionResult AddOrUpdate(Blog entity)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _blogRepository.AddOrUpdate(entity);
        //        TempData["Message"] = $"{entity.Title} Kayıt Edildi.";
        //        return RedirectToAction("List");
        //    }
        //    ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
        //    return View(entity);
        //}

        #endregion




    }
}

BlogApp.WebUI/ViewComponents/CategoryMenuViewComponent.cs
using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private ICategoryRepository _repository;
        public CategoryMenuViewComponent(ICategoryRepository repo)
        {
            _repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(_repository.GetAll());
        }
    }
}

BlogApp.WebUI/Views/Blog/AddOrUpdate.cshtml
@model Blog
@{
    ViewData["Title"] = "AddOrUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <h2>Add or Update</h2>
    <br />

    <form asp-controller="Blog" asp-action="AddOrUpdate" method="post">
        <input type="hidden" asp-for="BlogId" />
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Body"></label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Image"></label>
            <textarea asp-for="Image" class="form-control"></textarea>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsApproved" type="checkbox" class="form-check-input">
                Is Approved
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsHome" type="checkbox" class="form-check-input">
                Is Home
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsSlider" type="checkbox" class="form-check-input">
                Is Slider
            </label>
        </div>
        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories">
                <option disabled selected value="">
                    Select Category
                </option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>

</div>

BlogApp.WebUI/Views/Blog/Create.cshtml
@model Blog
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
        <h2>Create</h2>
        <br />

        <form asp-controller="Blog" asp-action="Create" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label asp-for="Body"></label>
                <textarea asp-for="Body" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="file" name="file" id="file" class="form-control" />
            </div>
            <div class="form-check">
                <label class="form-check-label">
                    <input asp-for="IsApproved" type="checkbox" class="form-check-input">
                    Is Approved
                </label>
            </div>
            <div class="form-check">
                <label class="form-check-label">
                    <input asp-for="IsHome" type="checkbox" class="form-check-input">
                    Is Home
                </label>
            </div>
            <div class="form-check">
                <label class="form-check-label">
                    <input asp-for="IsSlider" type="checkbox" class="form-check-input">
                    Is Slider
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories">
                    <option disabled selected value="">
                        Select Category
                    </option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>

    </div>








@*<div class="container">
        <h2>Create</h2>
        <br />

        <form asp-controller="Blog" asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories">
                    <option disabled selected value="">
                        Select Category
                    </option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>

    </div>*@

BlogApp.WebUI/Views/Blog/Delete.cshtml
@model Blog
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <div class="alert alert-warning">
        <h2>@Model.Title</h2> Kaydı Silmek İstiyor Musunuz ?
    </div>
    <form asp-controller="Blog" asp-action="Delete" method="post">
        <input type="hidden" asp-for="BlogId" />
        <button type="submit" class="btn btn-danger">Delete</button>

    </form>

</div>

BlogApp.WebUI/Views/Blog/Details.cshtml
@model Blog
@{
    ViewData["Title"] = "Details";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            <div class="card mb-2">
                <div class="card-header">
                    @Model.Title
                </div>
                <img class="card-img-top" src="~/img/@Model.Image" alt="@Model.Title">
                <div class="card-block">
                    <h5 class="card-title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">@Html.Raw(Model.Body)</p>
                    
                </div>
            </div>
        </div>
    </div>

</div>

BlogApp.WebUI/Views/Blog/Edit.cshtml
@model Blog
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section scripts{

    @*<script src="~/bower_components/ckeditor/ckeditor.js"></script>*@ @*Bunu görmedi*@
    <script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("Body");
    </script>
}

<div class="container">
    <h2>Edit</h2>
    <br />

    <form asp-controller="Blog" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="BlogId" />
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Body"></label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label>Image</label>
            <br />
            <img src="~/img/@Model.Image" width="120" />
            <input type="hidden" asp-for="Image" />
            <input type="file" name="file" id="file" class="form-control" />
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsApproved" type="checkbox" class="form-check-input">
                Is Approved
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsHome" type="checkbox" class="form-check-input">
                Is Home
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="IsSlider" type="checkbox" class="form-check-input">
                Is Slider
            </label>
        </div>
        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories">
                <option disabled selected value="">
                    Select Category
                </option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>

</div>

BlogApp.WebUI/Views/Blog/Index.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "Index";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_BlogList", Model)
        </div>
    </div>

</div>

BlogApp.WebUI/Views/Blog/List.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container mt-3">
    <h2>Blog List</h2>
    <hr />
    <div>
        <a class="btn btn-success" asp-controller="Blog" asp-action="Create">Create</a>
    </div>
    <hr />
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>Is Approved</th>
                            <th>Is Home</th>
                            <th>Is Slider</th>
                            <th>Transaction</th>
                            <th>Transaction</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.BlogId</td>
                            <td>
                                <img src="~/img/@item.Image" width="100" />
                            </td>
                            <td>@item.Title</td>
                            <td>@item.Date</td>
                            <td>

                                @if (item.IsApproved)
                                {
                                    <i class="fas fa-check" aria-hidden="true"></i>

                                }
                                else
                                {
                                    <i class="fas fa-times" aria-hidden="true"></i>
                                }
                            </td>
                            <td>
                                @if (item.IsHome)
                                {
                                    <i class="fas fa-check" aria-hidden="true"></i>

                                }
                                else
                                {
                                    <i class="fas fa-times" aria-hidden="true"></i>
                                }
                            </td>
                            <td>
                                @if (item.IsSlider)
                                {
                                    <i class="fas fa-check" aria-hidden="true"></i>

                                }
                                else
                                {
                                    <i class="fas fa-times" aria-hidden="true"></i>
                                }
                            </td>
                            <td><a class="btn btn-primary btn-sm" asp-controller="Blog" asp-action="Edit" asp-route-id="@item.BlogId">Edit</a></td>
                            <td><a class="btn btn-danger btn-sm" asp-controller="Blog" asp-action="Delete" asp-route-id="@item.BlogId">Delete</a></td>


                        </tr>
                        }

                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    Blog Eklenmemiştir.
                </div>
            }
        </div>
    </div>

</div>